In [2]:
%load_ext autoreload

import torch
import time
from torch.autograd import Variable
from torch.nn import ReLU
import numpy as np
from numpy import matlib as mb
import matplotlib.pyplot as plt
import scipy.io
from scipy.sparse import random as sprand
from scipy import stats
#%matplotlib qt
import matplotlib.cm as cm
from matplotlib.colors import Normalize, ListedColormap
# import dill
import os
from imageio import imread, imwrite
from torch.nn import ReLU
from sklearn.decomposition import PCA

import pandas as pd
import seaborn as sns

%matplotlib qt
ReLu = ReLU()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [26]:
%autoreload
from srnn_helpers import *

In [62]:
temp = torch.randn(3,7,5)
print(temp.shape)
print(temp[-1].shape)

torch.Size([3, 7, 5])
torch.Size([7, 5])


In [53]:
if 'a' or 'b' in ['bala','ab','ca','ac']:
    print('y')

y


In [54]:
if 1<0 or 1.0000000000001>1: print('yes') else: print'n'

SyntaxError: invalid syntax (<ipython-input-54-cacbfa97cbbc>, line 1)

In [24]:
a = torch.randn(100)
print(torch.min(torch.pow(ReLu(a),1),torch.tensor(2.)))

tensor([0.0000, 1.4656, 0.0000, 1.2141, 0.0000, 0.7130, 1.8557, 0.0000, 0.0000,
        0.0000, 0.1396, 0.0000, 0.0000, 1.1261, 0.0000, 1.1294, 0.0000, 0.0000,
        2.0000, 0.1713, 0.1282, 0.0000, 0.0000, 0.0000, 0.6891, 1.4334, 0.4791,
        1.0696, 0.0000, 1.8816, 1.2357, 0.6507, 0.0226, 0.0000, 1.8407, 1.5433,
        0.0000, 0.0139, 0.0000, 0.0566, 0.8225, 0.0000, 1.4207, 0.0000, 0.3394,
        0.0000, 2.0000, 0.2481, 0.2848, 1.9109, 0.9505, 0.0000, 1.3766, 0.7385,
        0.2213, 0.4994, 1.1024, 0.8361, 0.0954, 0.0000, 0.0000, 0.0348, 0.0000,
        0.0000, 1.7365, 0.0000, 0.0000, 0.0254, 0.5498, 0.0000, 0.0000, 0.1257,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9719, 0.7792, 0.0000, 0.0000,
        0.0000, 1.7349, 0.4600, 0.0000, 0.9821, 1.5700, 0.4144, 0.3566, 0.0000,
        0.0000, 0.3708, 0.0000, 1.3348, 0.0000, 1.0124, 0.0000, 0.0000, 1.2459,
        0.2460])


In [3]:
r = np.random.randn(21, 100)/5
r[:,50:] +=1
l = -np.ones([1,100])
l[:,50:] = 1

r_df = pd.DataFrame(r).stack().to_frame(name='readout_activity')
r_df = r_df.reset_index()
r_df['level_1'] = r_df['level_1'].map(lambda x: l[0,x])
r_df = r_df.rename(columns={'level_0':'Time Steps', 'level_1':'Pattern Label'})

In [4]:
r_df

Time Steps  Pattern Label  readout_activity
0              0           -1.0         -0.059761
1              0           -1.0         -0.167215
2              0           -1.0          0.024042
3              0           -1.0         -0.093956
4              0           -1.0          0.241460
...          ...            ...               ...
2095          20            1.0          0.909428
2096          20            1.0          1.070201
2097          20            1.0          0.998018
2098          20            1.0          1.154598
2099          20            1.0          0.746528

[2100 rows x 3 columns]

In [8]:
fig, axs = plt.subplots(2,3, figsize=(15,10))
ax = sns.violinplot(x='Time Steps', y='readout_activity', hue='Pattern Label',
                   data=r_df, palette=['r','b'], split=True, inner="quartile", ax=axs[0,1])
ax.scatter(np.arange(21), np.random.randn(21)/10+0.5, marker='4', s=500, c='orange')
ax.set_xlabel('Time steps (int)', fontsize=15)
ax.set_ylabel('Readout activity', fontsize=15)
ax.set_title('Readout Activity by pattern type (B+, R-)%s' % ('\n'+''), fontsize=15)
# ax.set_xlim([0,r.shape[0]-1])
ax.set_ylim([np.min(r), np.max(r)])
ax.set_xticks(np.arange(0,r.shape[0]+1,2))
ax.set_xticklabels(np.arange(0,r.shape[0]+1,2))
ax.grid(linewidth=0.2)

In [182]:
np.arange(0,r.shape[0]+1,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
a = {}
a[(0.01, 0.0001)] = [np.random.randn(100)]
a[(0.02, 0.0001)] = np.random.randn(100)
a[(0.02, 0.0001)] = np.random.randn(100)
a[0.01] = np.random.randn(100)

In [12]:
a.keys()

dict_keys([(0.01, 0.0001), (0.02, 0.0001), 0.01])

In [26]:
try: 
    a[0.01]
    print("true")
except KeyError:
    print("false")

true


In [27]:
a[0.01]
print("ala")

ala


In [4]:
torch.normal(torch.tensor(1),torch.tensor(1e-17),[10])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
%autoreload
from srnn_helpers import *

In [98]:
a = np.random.randn(20,5)
b = np.random.randn(20,5) + 10*np.ones(5)
c = np.vstack([a,b])
print(c.shape)
plt.figure()
plt.scatter(c[:,0],c[:,1])
plt.figure()
plt.scatter(c[:,1],c[:,2])

pca = PCA(n_components=5)
d = pca.fit_transform(c)
plt.figure()
plt.scatter(d[:,0],d[:,1])
plt.figure()
plt.scatter(d[:,1],d[:,2])


(40, 5)


In [87]:
a = torch.randn(1)
print(a.shape)
b = torch.randn(10,3)
print(b.shape)
print(a)
print(a-b)

torch.Size([1])
torch.Size([10, 3])
tensor([0.1736])
tensor([[ 0.0476, -0.2286, -1.1532],
        [ 0.0622, -0.2506, -0.6347],
        [ 0.4678,  0.6582,  1.1048],
        [ 0.8107,  0.3908,  0.8166],
        [ 0.3767, -1.4248,  0.7782],
        [-0.4910,  1.0994, -0.9384],
        [-0.5148,  0.2713,  0.4488],
        [-0.1757,  0.9069, -0.3541],
        [-0.8433,  1.0702,  1.8454],
        [-0.6640, -0.4428, -0.5149]])


In [77]:
N=30
np.array([np.arange(N),np.arange(N)]).shape

(2, 30)

In [69]:
fig, axs = plt.subplots()
axs.plot(np.random.randn(10))
plt.show()

In [74]:
np.max(np.random.randn(20))

TypeError: _amax_dispatcher() got multiple values for argument 'axis'

In [54]:
a = np.zeros([4,8])*np.nan
a[:2]=1
print(a)
print(a[~np.isnan(a)])

[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [55]:
~np.isnan(a)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [33]:
def test_fun(**inp):
    """ test function """
    return inp['a'] + inp['d']

In [34]:
print(test_fun.__doc__)
test_fun.__doc__ = 'changed test function'
print(test_fun.__doc__)
print(test_fun(a=1,b=2,c=3,d=4))

 test function 
changed test function
5


In [44]:
P = 15
a = torch.randn(2,10)
labels = 2 * np.random.randint(0,2,(1,P)) - 1
ids_positive_label = np.where(labels==1)[1]
ids_negative_label = np.where(labels==-1)[1]
b = a[((-labels+1)//2)[0]]
print(a)
print(labels)
print(a.shape)
print(b[np.random.permutation(P)[:20]].shape)
print()
print(ids_positive_label.shape)
print(a[np.zeros(ids_positive_label.shape[0])])

tensor([[-1.4051,  0.1933, -0.5782, -1.0555, -0.5328, -1.5879,  0.3730, -0.5636,
          0.1030,  0.9595],
        [ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706]])
[[-1  1 -1  1 -1 -1 -1  1 -1  1  1  1  1  1 -1]]
torch.Size([2, 10])
torch.Size([15, 10])

(8,)
tensor([[-1.4051,  0.1933, -0.5782, -1.0555, -0.5328, -1.5879,  0.3730, -0.5636,
          0.1030,  0.9595],
        [-1.4051,  0.1933, -0.5782, -1.0555, -0.5328, -1.5879,  0.3730, -0.5636,
          0.1030,  0.9595],
        [-1.4051,  0.1933, -0.5782, -1.0555, -0.5328, -1.5879,  0.3730, -0.5636,
          0.1030,  0.9595],
        [-1.4051,  0.1933, -0.5782, -1.0555, -0.5328, -1.5879,  0.3730, -0.5636,
          0.1030,  0.9595],
        [-1.4051,  0.1933, -0.5782, -1.0555, -0.5328, -1.5879,  0.3730, -0.5636,
          0.1030,  0.9595],
        [-1.4051,  0.1933, -0.5782, -1.0555, -0.5328, -1.5879,  0.3730, -0.5636,
          0.1030,  0.9595],
        [-1.4051,  0.1933, -0.5

In [46]:
print(a[np.ones(ids_negative_label.shape[0])])

tensor([[ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706],
        [ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706],
        [ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706],
        [ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706],
        [ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706],
        [ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706],
        [ 0.7811,  0.6402, -1.1970, -1.1456,  1.1404, -1.1048, -0.1322,  0.9531,
         -0.9229, -0.6706]])


In [ ]:
a = np.zeros(10)#*np.nan
a[:4] = np.random.randn(4)
plt.scatter(np.arange(len(a)),a)

In [ ]:
a = torch.randn(3,10)
b = a.mean(0)
print(a)
print(a.shape)
print(b)
print(b.shape)
plt.figure(1)
plt.scatter(20-np.arange(len(b)),b,marker='4', s=500, c='green')

In [ ]:
P = 5
NT = 3
a = torch.randn(NT,P)
labels = 2 * np.random.randint(0,2,(1,P)) - 1
ids_positive_label = np.where(labels==1)[1]
ids_negative_label = np.where(labels==-1)[1]

print(a)
print(ids_positive_label)
print(a[[-1],ids_positive_label])
print((torch.tensor(1) - torch.tanh(a[-1,ids_positive_label])).sum() + \
      (torch.tanh(a[-1,ids_negative_label])-torch.tensor(-1)).sum())

In [ ]:
print(a[-1,ids_positive_label])
print(a.shape)
print(a[-1,ids_positive_label])
print("test", a[-5:])

In [ ]:
a.mean(0)[-1].shape == torch.tensor(1).shape

In [ ]:
P = 5
NT = 3
readout_activity_numpy = np.random.randn(P,NT)
labels = 2 * np.random.randint(0,2,(1,P)) - 1

thresh = np.percentile(readout_activity_numpy, 100 * (np.sum(labels==-1)/P), axis=0)
output_label = 2 * (readout_activity_numpy > thresh) - 1
accuracy = 100*np.sum((output_label * labels.T)>0,0)/P

print(readout_activity_numpy)
print(readout_activity_numpy.shape)
print(labels.shape)
print(thresh)
print(100 * (np.sum(labels==-1)/P))
print(thresh.shape)
print(output_label)
print(output_label.shape)
print(output_label * labels.T)
print(accuracy)
print(np.max(accuracy))

In [ ]:
a = torch.normal(0,10,[3,4])
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a)
print(a.requires_grad)

b = torch.rand([3,4])>0.5
print(b)
print(a*b)

c = torch.ones([1,4])
c[:,[0,3]] = -1
print(c)
print(a*c)
print(torch.sign(a*c))
print(a*torch.sign(a*c))

In [ ]:
c.data.cpu().numpy().shape

In [ ]:
N=3
P=4
patterns = torch.tensor(2 * np.random.rand(N,P) - 1)
labels = 2 * np.random.randint(0,2,(1,P)) - 1

print(patterns)
print(patterns.T)
print(patterns @ patterns.T)
print(torch.mm(patterns,patterns.T))
print(labels)
print(patterns*labels @ patterns.T)

In [ ]:
torch.set_default_tensor_type(torch.DoubleTensor)
b0 = np.zeros(21)  # input pulse 
b0[:10] = 1
b = torch.tensor(b0)
print(b0)
print(b)
c = torch.zeros(21, dtype=torch.float32)
c[:10]=1
print(c)
print(c.dtype)

In [ ]:
rtarg0 = np.array([[0.        , 0.01549421, 0.03024185, 0.04414475, 0.05721401,
        0.06937062, 0.08062606, 0.09099244, 0.10050713, 0.10932685,
        0.09942289, 0.09062364, 0.08274024, 0.07564845, 0.06922923,
        0.06345079, 0.05821675, 0.05346545, 0.04914874, 0.0452366 ,
        0.04172525],
       [0.        , 0.01219308, 0.02369528, 0.03442936, 0.04436093,
        0.05349317, 0.06185797, 0.06948947, 0.07623375, 0.08226423,
        0.07297895, 0.064946  , 0.05795353, 0.05186845, 0.04657435,
        0.04192478, 0.03784535, 0.03426677, 0.0310036 , 0.02813408,
        0.02558498]])
rtarg = torch.tensor(rtarg0)
id_positive = np.where(labels==1)[1]  # ids of the +1 patterns
id_negative = np.where(labels==-1)[1]  # ids of the -1 patterns
print(id_positive)

In [ ]:
rtarg[((-labels+1)//2)[0]][id_positive]

In [ ]:
def test():
    """ala bala"""
    print(0)
    pass


In [ ]:
test.__doc__

In [ ]:
a = np.zeros(4)
a[:3] = 1
print(a)
for i in range(1,len(a)):
    print(a[i])

In [ ]:
N=50
P=100
patterns = 2 * np.random.rand(N,P) - 1
labels = 2 * np.random.randint(0,2,(1,P)) - 1

In [ ]:
patterns.shape

In [ ]:
labels.shape

In [ ]:
patterns

In [ ]:
labels

In [ ]:
patterns * labels

In [ ]:
np.where(labels==1)